import type { Metadata } from "next";
import {
  Geist_Mono,
  Nunito,
  Plus_Jakarta_Sans,
  Syne_Mono,
} from "next/font/google";
import "./globals.css";
import { cn } from "./lib/utils";
import Navbar from "@/app/components/Navbar";

const geistSans = Geist_Mono({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const nunitoSans = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const syne = Syne_Mono({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-syne",
});

export const metadata: Metadata = {
  title: "Settled",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        geistSans.variable,
        nunitoSans.variable,
        jakartaSans.variable,
        syne.variable,
        " h-full antialiased",
      )}
    >
      <body className="min-h-full overflow-x-hidden">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
